### ISSUE TITLE
Wrong NDK binary paths on linux x86

### ISSUE THREAD

**Issue by mvdan** [teknoraver/andhrystone#1]
This might apply to other architectures and OSes too.

You are trying to use the NDK on linux x86 like so:

`$ANDROID_NDK/toolchains/x86-4.9/prebuilt/linux-i686/bin/i686-linux-android-gcc`

But the correct path is:

`$ANDROID_NDK/toolchains/x86-4.9/prebuilt/linux-x86/bin/i686-linux-android-gcc`

This is why the build is failing on F-Droid.

**Comment by teknoraver** [comment]
Sorry, I never did a 32 bit build, I confirm it builds fine on amd64.
Fixed in new rev 1.4.2
